# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: 'America/Chicago'
    volumes:
      - etc-pihole:/etc/pihole'
    deploy:
      restart_policy:
        contitions: on-failure
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  etc-pihole:
