version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - watchtower
    ports:
      - 8003:8080
    envrionment:
      TZ: America/Chicago
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: ${EMAIL_SERVER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_USER: ${EMAIL_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${EMAIL_FROM}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${EMAIL_TO}

networks:
  watchtower:
    extenal: true
