name: adguard

services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - config:/opt/adguardhome/conf
      - work:/opt/adguardhome/work
    restart: unless-stopped

volumes:
  config:
  work: