services:
  twingate_connector:
    container_name: ${SERVER_NAME}
    restart: always
    image: "twingate/connector:latest"
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${REFRESH_TOKEN}
      - TWINGATE_LOG_ANALYTICS=v2
      - TWINGATE_LOG_LEVEL=3
    network_mode: host

