---

- hosts: "*"
  become: yes
  tasks:
    
    - name: Upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        update_cache: 'yes'

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get Ubuntu Version
      command: "lsb_release -cs"
      register: ubuntu_version

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=armhf] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: Update apt cache
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes